# resources
# folder where the program search files
resources_dir: ../resources
export_dir: files
# folder where the program search sounds 
sounds_dir: "../resources/sounds"

# mode
# read or reduction
# read take a file with reducted vectors
# reduction take a file with embeddings
mode: "reduction"

# reduction properties (mode=reduction)
# LDA or UMAP or LDA,UMAP
reductionMethod: UMAP
# file where the embeddings are
xvectorsFile: /dataset/Spk/train_data/xvectors.txt
# "" = all variables, "best" variables with biggest extend, "worst" variables with the lowest extend
variableSelectionOption: ""
# if option set, define the number of variables selected
variablesSelectionNumber: 20
# file to store the reducted vectors
exportReductionFile: emb2DTEST.txt

# UMAP
# number of dimension
dimension: 2
# smaller = more local preservation (default: 15)
n_neighbor: 15
# min_dist (default 0.1)
min_dist: 0.1
# if true load the UMAP model
loadUmapModel: true
# saving the UMAP model
saveUmapModelFile: "umapModel"
# loading the UMAP model
loadUmapModelFile: "umapModel"

# LDA
# if true load the LDA model
loadLdaModel: true
# saving the LDA model
saveLdaModelFile: "ldaModel"
# loading the LDA model
loadLdaModelFile: "ldaModel"

# no reduction	(mode=read)
readingFile: emb2D.txt

# plot properties
# file to save the plot
plotFile: plot/test.jpg
# Activate the plot autonaming
autoNamePlot: false
# showing the plot or not
showPlot: True
# size of the dot (default=15) 
dotSize: 10
# size of the edge of the dot (default=0.5) 
dotLineWidth: 0.25
# size of the prototype and the criticism (default=20) 
protoSize: 25
# size of the edge of the prototype and the criticism (default=1) 
protoLineWidth: 1.25
oneDotPerSpeaker: false
detailSpeakerClick: True

# prototypes
# calculate prototypes and criticisms if true
findProto: true
eachSpeaker: true
nbProto: 2
# if find proto is true, choose before or after UMAP
afterReduction: true
# define the distance calculation
kernel: euclidienne
# if find proto is true, calculate the distance between prototypes and criticisms
gridSearch: false

readingProto: true
saveFiles: True
protoFile: proto.txt
critFile: crit.txt
uttFile: utt.txt
