# resources
# folder where the program search files
resources_dir: ../resources
# folder where the program search sounds 
sounds_dir: "../resources/sounds"

# mode
# read or reduction
# read take a file with reducted vectors
# reduction take a file with embeddings
mode: "reduction"

# reduction properties (mode=reduction)
# file where the embeddings are
xvectorsFile: "xvectors.txt"
# "" = all variables, "best" variables with biggest extend, "worst" variables with the lowest extend
variableSelectionOption: ""
# if option set, define the number of variables selected
variablesSelectionNumber: 20
# file to store the reducted vectors
exportReductionFile: emb2DTEST.txt
# UMAP
# number of dimension
dimension: 2
# smaller = more local preservation (default: 15)
n_neighbor: 15
# min_dist (default 0.1)
min_dist: 0.2

# no reduction	(mode=read)
readingFile: emb2D.txt

# plot properties
# file to save the plot
plotFile: "plot/plotM02.jpg"
# showing the plot or not
showPlot: False
# size of the dot (default=20) 
dotSize: 20

# prototypes
# calculate prototypes and criticisms if true
findProto: True
# if find proto is true, calculate the distance between prototypes and criticisms
gridSearch: True