# resources
# folder where the program search files
resources_dir: ../resources
export_dir: files
# folder where the program search sounds 
sounds_dir: "../resources/sounds"

# mode
# read or reduction
# read take a file with reducted vectors
# reduction take a file with embeddings
mode: "reduction"

# reduction properties (mode=reduction)
# LDA or UMAP or LDA,UMAP
reductionMethod: UMAP
# file where the embeddings are
# xvectorsFile: /files/SET1/xvectorsS1.txt
xvectorsFile: /2speakersVectors.txt
# "" = all variables, "best" variables with biggest extend, "worst" variables with the lowest extend
variableSelectionOption: ""
# if option set, define the number of variables selected
variablesSelectionNumber: 20
# file to store the reducted vectors
#exportReductionFile: emb2DTEST.txt

# UMAP
# number of dimension
dimension: 2
# smaller = more local preservation (default: 15)
n_neighbor: 15
# min_dist (default 0.1)
min_dist: 0.1
# if true load the UMAP model
loadUmapModel: true
# saving the UMAP model
saveUmapModelFile: "/UMAPTest"
# loading the UMAP model
loadUmapModelFile: "/UMAPTest"

# LDA
# if true load the LDA model
loadLdaModel: true
# saving the LDA model
saveLdaModelFile: "ldaModel"
# loading the LDA model
loadLdaModelFile: "ldaModel"



# plot properties
# file to save the plot
plotFile: plot/test.jpg
# Activate the plot autonaming
autoNamePlot: false
# showing the plot or not
showPlot: true
# size of the dot (default=15) 
dotSize: 10
# size of the edge of the dot (default=0.5) 
dotLineWidth: 0.25
# size of the prototype and the criticism (default=20) 
protoSize: 25
# size of the edge of the prototype and the criticism (default=1) 
protoLineWidth: 1.25
oneDotPerSpeaker: true
detailSpeakerClick: true

# prototypes
# calculate prototypes and criticisms if true
findProto: true
eachSpeaker: true
nbProto: 2
# if find proto is true, choose before or after UMAP
afterReduction: true
# define the distance calculation
kernel: euclidienne
# if find proto is true, calculate the distance between prototypes and criticisms
gridSearch: true

# no reduction  (mode=read)
# reading proto and crit
readingProto: true
# save files or not (if mode==reduction)
saveFiles: True
# files names 
protoFile: "/SET4Reducted/S4T3proto.txt"
critFile: "/SET4Reducted/S4T3crit.txt"
uttFile: "/SET4Reducted/S4T3utt.txt"


reducedUtterances: true
# number of speaker in a group for calculating prototypes and criticisms
groupSize: 20