# resources
# folder where the program search files
resources_dir: ../resources
# folder where the program search sounds 
sounds_dir: "../resources/sounds"

# mode
# read or reduction
# read take a file with reducted vectors
# reduction take a file with embeddings
mode: "read"

# reduction properties (mode=reduction)
# LDA or UMAP or LDA,UMAP
reductionMethod: UMAP
# file where the embeddings are
xvectorsFile: xvectors.txt
# "" = all variables, "best" variables with biggest extend, "worst" variables with the lowest extend
variableSelectionOption: ""
# if option set, define the number of variables selected
variablesSelectionNumber: 20
# file to store the reducted vectors
exportReductionFile: emb2DTEST.txt
# UMAP
# number of dimension
dimension: 2
# smaller = more local preservation (default: 15)
n_neighbor: 15
# min_dist (default 0.1)
min_dist: 0.1
# saving the UMAP model
saveModel: "umapModel"
# loading the UMAP model
loadModel: "umapModel"

# no reduction	(mode=read)
readingFile: emb2D.txt

# plot properties
# file to save the plot
plotFile: plot/test.jpg
# Activate the plot autonaming
autoNamePlot: False
# showing the plot or not
showPlot: True
# size of the dot (default=20) 
dotSize: 20

# prototypes
# calculate prototypes and criticisms if true
findProto: True
# if find proto is true, choose before or after UMAP
afterReduction: True
# if find proto is true, calculate the distance between prototypes and criticisms
gridSearch: True